// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obpczrwjzsihtvuyoyul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9icGN6cndqenNpaHR2dXlveXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTkwODIsImV4cCI6MjA2NTczNTA4Mn0.mp-0y8mDyG_9fuV2l1rNWF8-7rt624HVtz5VFWGhGzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);